---
title: "R Notebook"
output: html_notebook
---

# Facebook birthdays 

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
birthdays <- read.csv('birthdaysExample.csv')

birthdays <-
separate(birthdays, dates, c("month", "day", "year"), sep = "/")

birthdays %>% group_by(year, month) %>% summarise(num = n()) %>% arrange(desc(num)) %>% top_n(1)

birthday_days_tops <-
birthdays %>% group_by(year, month, day) %>% summarise(num = n()) %>% arrange(desc(num)) %>% top_n(1) %>% unite(date, year, month, day, sep =
'-', remove = TRUE)

birthdays %>% group_by(year, month, day) %>% summarise(num = n()) %>% arrange(desc(num)) %>% filter(num == 0)

ggplot(data = birthdays, mapping = aes(x = month)) + geom_bar()
ggplot(data = birthday_days_tops, mapping = aes(x = date, y = num)) +  geom_bar(stat="identity")




```

```{r}

```


March is the month with the most birthdays

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
