---
title: 'Exploration baseball data'
output:
  html_document: default
  html_notebook: default
  pdf_document: default
---

```{r  echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)
library(GGally)
```


```{r}
df <- read.csv('data/baseball_data.csv')
```

```{r}
df[duplicated(df$name),]
```

```{r}

df$HR_normalized = (df$HR - min(df$HR))/(max(df$HR) - min(df$HR))
df$avg_normalized = (df$avg - min(df$avg))/(max(df$avg) - min(df$avg))
df$valuability = df$avg_normalized + df$HR_normalized 
df$valuability_normalized = (df$valuability - 
                            min(df$valuability))/(max(df$valuability) 
                              - min(df$valuability)) 

df$bmi = (df$weight * 0.4535923) / (2.54 * df$height / 100 * 2.54 *df$height / 100)

df$weight_bin = cut(df$weight,
                   c(0,175,200,400),
                   labels = c('light (-175)',
                              'average (175-200)', 'heavy (200-)'))
df$height_bin = cut(df$height,
                   c(0,70,73,100),
                   labels = c('short (-70)',
                              'average (70-73)', 'tall (73-)'))

df$bmi_bin = cut(df$bmi,
                   c(0,22,24,26,28,50),
                   labels = c('very low (-22)',
                              'low (22-24)', 'average (24-26)', 'high (26-28)', 'very high (28-)'))

df[is.na(df)] <- 0


df$name = make.unique(as.character(df$name))
```

```{r}

write.csv(df, 'data/baseball_data.csv', quote=FALSE, row.names = FALSE)
```



```{r}
str(df)
```




```{r warning=FALSE, echo=FALSE, fig.height=10, fig.width=20, message=FALSE}
ggpairs(df[, -which(names(df) %in% c('name'))])
```


