---
title: "Data Visualization with Tableau"
output:
  pdf_document: default
  html_document: default
---

by Jens Laufer, 15/08/2017




## Summary


The performance of 1157 baseball players was evaluated in this data analysis.
The dataset contains 5 variables.

The goal of this project is to visualize a finding in the data with a Tableau
story.



## Data Set Exploration


The data was first analysed with a R notebook to check the data and get
a first impression.

   1. The data set was checked for problematic data:
   
      All features are available 
      and valid. 
      
      There are some players with duplicated names:
      
        - Dave Roberts 
        
        - Bobby Mitchell
        
        - Mike Brown
        
        - Dave Stapleton 
        
        - Jim Wright
        
        - Mel Stottlemyre
        
      For the second player with the same name ".1" was assigned to the name 
      to distinguish the duplicate
      players.

   2. Additional fields were added. This was done with R, as the MinMax-Scaling was difficult
      in Tableau:

      
      | Field              | Description                                             |
      | ------------------ | ------------------------------------------------------- |
      | HR_normalized      | Scaled value of HR  (min=0, max=1)                      |
      | avg_normalized     | Scaled value of avg (min=0, max=1)                      |
      | valuability        | Sum of HR_normalized and avg_normalized                 |
      | bmi                | Body mass index (BMI)                                   |
      | weight_bin         | Bins for weight                                         |
      | height_bin         | Bins for height                                         |
      | bmi_bin            | Bins for BMI                                            |
      
      The HR and avg field was normalized (MinMax) for the aggregation of a new 
      performance field: Valuability is the addition of the normalized
      HR and avg. It's the overall value of a player. 
      
      The field body mass index (BMI) was aggregated from weight and height.
      
      Bins were created for height, weight and BMI.

   4. The modified dataset was then exported to a new CSV, which is used within
      Tableau.

   5. A correlation matrix was then plotted with R, as it was a simple way to
      visualize the data and correlations between the features to get a first 
      impression of the data. 

   6. The data was then handed over to Tableau for the in deep explorative data 
      analysis.



## Design


For the visualization of top performers bar charts were used as they show a 
trend in the data in a simple way and make it easy to compare the performance
of the players for the reader by comparing the lenghth of the bars. 
I used different colors to distinguish the 
different type of performances. 

For the visualization of height and weight I used a scatter plot as scatter plots
are good to visualize more than two variables. The plot is facetted with the
data for the top 10 players and all other players. A color is also used for the
top 10 players to stress the top 10 players even more.

Throughout all visualizations colors were used, but it was tried to reduce number
of colors to not confuse the reader.

The number of visualization on a story point was reduced to a minimum for easy
understanding of the findings.



### Iteration 1

#### Story Point 1

Two barchart with the names of the top homerunners and  the 
players with the highest batting average with different colors for the homeruns
and batting average are used. The size of the bars was reduced 
and a dot was added at the end of the bar.
All "chunk" from the bar charts was removed like grid line and axis labels, 
to make the visualization lightweight and clear.


#### Story Point 2

The barchart from Story Point 1 for the top homerunners was reused, 
but the color of the bars was changed.
The color is the BMI bin. As there are just 3 BMI bins the reader can easily 
understand the meaning of the color.

Below the barchart simple scatterplots for BMI, weight and height are added.
The reader can easily see where a player is on the scale of this data.

Highlight actions to let the user select (or mouseover) a player on
either the scatterplots or on the barchart are added.


#### Story Point 3

The barchart from Story Point 1 for the top 10 players with the highest
batting average was resused. For the color of the bar the handedness is used
to visualize the handedness of the players in a simple way.

Scatterplots for BMI, weight and height with highlight actions are used in a
similiar way to story point 2.


##### Feedback (from Nadine Dernoschek)

Story Point 1 

  - I miss a number for home runs/batting average at least for the 
    first and last player.
  
Story Point 2/3:

  - I feel overwhelmed with the names appearing in chart above and below.
    It took me a while to understand what I see.
  - I'd like to have stronger gridlines for weight/height/BMI
  - I'd like to have either all names or none.


### Iteration 2

Tooltips were improved and reformatted. 

Fixed typos in text.

#### Story Point 1

The metric for the first and last bar was added.

#### Story Point 2/3


The metric for the first and last bar was added.
 
Names in Scatterplots were removed.

#### Feedback (from Manuel Armbruster)

   - I don't understand the plots below card 2 and 3.
   
   - The BMI legend with 'average', 'low' and 'high' is not sorted
   
   - I don't like that I have to scroll to the bottom. The height of the cards
     is too big.
     
### Iteration 3 (final)  

#### Story Point 1

Unchanged

#### Story Point 2

I added  2 scatter plot with the height and weight on the axises. The one
scatterplot is for the top 10 players (using same color in barchart) and the
players who are not in the top 10. This chart has more value for the reader

#### Story Point 3

I added 2 bar charts  with the handedness of the top 10 players 
and the other players.
The reader can now better compare these two groups.

#### Story Point 4

I added 2 bar charts with the body mass index (BMi) for the top 10 homerunners 
and for the top 10 players with the highest batting average. The reader can
easily see now the diffrence between the groups

##### Feedback (Manuel Armbruster, Nadine Dernoschek)

   - Much better now! (Manuel)
   
   - I like the simplicity of your charts (Nadine Dernoschek)


## Files


   - [Original Data (CSV)](data/baseball_data.csv)
   
   - [Modified Data (CSV)](data/baseball_data_updated.csv)

   - [Data Cleaning and Exploration with R](exploration.html)


## Visualizations


Data Exploration with Tableau:

   - [Tableau Data Exploration](https://public.tableau.com/views/exploration_baseball/Histogramheight?:embed=y&:display_count=yes)



Tableau Story Iteration 1:

   - [Comparison of Baseball Players V1](https://public.tableau.com/views/explanation_baseball_v1/ComparisonofBaseballPlayers?:embed=y&:display_count=yes)



Tableau Story Iteration 2:

   - [Comparison of Baseball Players V2](https://public.tableau.com/profile/jenslaufer#!/vizhome/explanation_baseball_v2/ComparisonofBaseballPlayers?publish=yes)



Tableau Story Iteration 3 (final):

   - [Comparison of Baseball Players V3](https://public.tableau.com/profile/jenslaufer#!/vizhome/explanation_baseball_v3/ComparisonofBaseballPlayers?publish=yes)

## Resources


[Tableau Community](https://community.tableau.com)

[Data Visualization Principles: Lessons from Tufte](https://moz.com/blog/data-visualization-principles-lessons-from-tufte)

[Wikipedia: Batting Average](https://de.wikipedia.org/wiki/Batting_Average)

[Wikipedia: Home Run](https://de.wikipedia.org/wiki/Home_Run)
