---
title: "Diamond bivariate analysis"
output:
  pdf_document: default
  html_notebook: default
---
 

```{r loading libraries}
library(ggplot2)
?diamonds
```

```{r Scatterplot}
ggplot(data=diamonds,mapping=aes(x=x,y=price)) +
  geom_point()
```
```{r}
with(diamonds, cor.test(price,x))
```
```{r}
with(diamonds, cor.test(price,y))
```

```{r}
with(diamonds, cor.test(price,z))
```

```{r}
ggplot(data=diamonds, mapping=aes(x=depth,y=price))+
  geom_point(alpha=1/70)+
  scale_x_continuous(breaks = seq(57,67,1), limits = c(55,68)) 
```
```{r}
with(diamonds, cor.test(price,depth))
```
```{r}
diamonds.carat.top1pct <- quantile(diamonds$carat, probs = c(0.99))
diamonds.price.top1pct <- quantile(diamonds$price, probs = c(0.99))

diamonds.carat.top1pct

ggplot(mapping=aes(x=carat, y=price), data=subset(diamonds, price < diamonds.price.top1pct& carat < diamonds.carat.top1pct))+
  geom_jitter(alpha=1/50)
```
```{r}
diamonds$volume = diamonds$x * diamonds$y * diamonds$z
```

```{r}
ggplot(mapping=aes(x=volume,y=price), data=diamonds) +
  geom_jitter() 

nrow(subset(diamonds,volume==0))
```

```{r}
diamonds.without.outliers <- subset(diamonds, diamonds$volume >0 & diamonds$volume <800)
cor.test(diamonds.without.outliers$price, diamonds.without.outliers$volume)
```
```{r}
ggplot(mapping=aes(x=volume, y=price), data=diamonds.without.outliers) +
  geom_point(alpha=1/100) +
  geom_smooth(method = 'lm')
```

```{r}
# Use the function dplyr package
# to create a new data frame containing
# info on diamonds by clarity.

# Name the data frame diamondsByClarity

# The data frame should contain the following
# variables in this order.

#       (1) mean_price
#       (2) median_price
#       (3) min_price
#       (4) max_price
#       (5) n

# where n is the number of diamonds in each
# level of clarity.

# This assignment WILL BE automatically
# graded!
library(dplyr)

diamondsByClarity <- diamonds %>% group_by(clarity) %>% summarize('mean_price'=mean(price),'median_price'=median(price),'min_price'=min(price), 'max_price'=max(price),'n'=n())

diamondsByClarity
```


```{r}

diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))
library(gridExtra)

p1 <- ggplot(data=diamonds_mp_by_clarity, mapping=aes(x=clarity, y=mean_price)) +
  geom_bar(stat = "identity")

p2 <- ggplot(data=diamonds_mp_by_color, mapping=aes(x=color, y=mean_price)) +
  geom_bar(stat = "identity")
  
grid.arrange(p1,p2, nrow=1)
```



