---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
pf <- read.csv('../lesson4/data/pseudo_facebook.tsv', sep = '\t')
```

```{r}
pf.fc_by_age_gender <- pf %>% group_by(age, gender) %>% filter(!is.na(gender)) %>% summarize(mean_friend_count=mean(friend_count),median_friend_count=median(friend_count), n=n()) %>% ungroup() %>% arrange(age)
head(pf.fc_by_age_gender)

```
```{r}
ggplot(data=pf.fc_by_age_gender, mapping=aes(x=age, y=mean_friend_count, color=gender)) + geom_line() 
```

```{r}
library(reshape2)

pf.fc_by_age_gender.wide <- dcast(pf.fc_by_age_gender,age ~ gender,
      value.var = 'median_friend_count')
```

```{r}
pf.fc_by_age_gender.wide$ratio <- pf.fc_by_age_gender.wide$female/pf.fc_by_age_gender.wide$male

ggplot(mapping=aes(x=age,y=ratio), data=pf.fc_by_age_gender.wide) + geom_line()+
geom_hline(yintercept = 1 ,alpha = 0.3, linetype = 1)
```


```{r}
pf$year_joined = 2014 - ceiling(pf$tenure /365)
pf$year_joined.bucket <-  cut(pf$year_joined, breaks = c(2004,2009,2011,2012,2014))
table(pf$year_joined.bucket)
```

```{r}
ggplot(aes(x = age, y = friend_count), 
              data = subset(pf, !is.na(year_joined.bucket))) + 
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)

```
```{r}

ggplot(aes(x = age, y = friend_count), 
              data = subset(pf, !is.na(year_joined.bucket))) + 
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = mean) +
  geom_line(stat='summary', fun.y=mean, linetype=3, alpha=.8)
```
```{r}
pf$friending_rate <- pf$friend_count / pf$tenure

pf.at.least.one.day.tenure <- subset(pf, tenure >= 1)

median(pf.at.least.one.day.tenure$friending_rate)
max(pf.at.least.one.day.tenure$friending_rate)

with(subset(pf, tenure >= 1), summary(friend_count/tenure))
```
```{r}
ggplot(mapping=aes(x=tenure, y=friendships_initiated/tenure), data=subset(pf, tenure >= 1)) +
  geom_line(aes(color=year_joined.bucket),stat='summary', fun.y=mean)
```
```{r}

ggplot(mapping=aes(x = 5 * round(tenure / 5), y=friendships_initiated/tenure), data=subset(pf, tenure >= 1)) +
  geom_smooth(aes(color=year_joined.bucket))
```

```{r}

ggplot(mapping=aes(x = 25 * round(tenure / 25), y=friendships_initiated/tenure), data=subset(pf, tenure >= 1)) +
  geom_smooth(aes(color=year_joined.bucket))

```

```{r}
ggplot
```

